$ANSIBLE_VAULT;1.1;AES256
66386439653765383566643464613464643464653738653939386166663732363761653234376630
3438646666643965383834663736643938653965383435310a666434346464396662633965383937
62633936396665326464643832376534643835633138653463383566663965383937626639653965
3835633138653463380a353938373464643965383937626639653965383937626639653965383937
62633936396665326464643832376534643835633138653463383566663965383937626639653965
3835633138653463380a353938373464643965383937626639653965383937626639653965383937
62633936396665326464643832376534643835633138653463383566663965383937626639653965
3835633138653463380a353938373464643965383937626639653965383937626639653965383937