---
# Python role variables

# OS-specific Python packages
python_packages_by_os:
  Debian:
    - python3
    - python3-pip
    - python3-venv
    - python3-dev
    - python3-setuptools
    - python3-wheel
    - python3-distutils
  RedHat:
    - python3
    - python3-pip
    - python3-devel
    - python3-setuptools
    - python3-wheel

# Python executable paths
python_executable:
  Debian: /usr/bin/python3
  RedHat: /usr/bin/python3

# Pip executable paths
pip_executable:
  Debian: /usr/bin/pip3
  RedHat: /usr/bin/pip3